### ISSUE TITLE
Broken links references of primer!

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/honeybee-primer#1]
Hi @mostaphaRoudsari,
These references links of honeybee primer are broken:

http://plea-arch.org/PLEA/ConferenceResources/PLEA2004/Proceedings/p1153final.pdf
http://apps1.eere.energy.gov/buildings/energyplus/pdfs/inputoutputreference.pdf

also these links of Ladybug primer:

http://apps1.eere.energy.gov/buildings/energyplus/pdfs/auxiliaryprograms.pdf
http://www.buildingenergysoftwaretools.com/software.cfm/ID=123/pagename=alpha_list
http://www.nrcan.gc.ca/energy/software-tools/7465/download.php/ang/120/0/Textbook_SWH.pdf
http://www.gsd.harvard.edu/research/gsdsquare/Publications/Shaderade_BS2011.pdf

Best regards,
-Omid

**Comment by mostaphaRoudsari** [comment]
Hi @Omidmr,
Thank you for reporting. We need to find the correct links and replace them.
cc: @chriswmackey

**Comment by chriswmackey** [comment]
My gosh, the web changes so fast. @mostapharoudsari , I will fix these in the component descriptions soon and post back here. Once I do so, you can run the script to update the primer.

-Chris

**Comment by chriswmackey** [comment]
@Omidmr ,

Thanks again for finding all of the broken links.  I have fixed all that I could within the components but there are still 3 that still remain.  @Omidmr , I could not find these 2 links within the Ladybug Primer:
http://www.buildingenergysoftwaretools.com/software.cfm/ID=123/pagename=alpha_list
http://www.nrcan.gc.ca/energy/software-tools/7465/download.php/ang/120/0/Textbook_SWH.pdf
Could you point me towards them?

@mostaphaRoudsari there is 1 link that you added in the GenCumSky component and I don't know where to find an updated version of the PDF:
http://plea-arch.org/PLEA/ConferenceResources/PLEA2004/Proceedings/p1153final.pdf

Once we fix everything in the components, @mostaphaRoudsari can run the script that updates the primers and we can close out the issue.

Thanks again,
-Chris

**Comment by Omidmr** [comment]
Hi @chriswmackey,
Thanks for finding correct links.

 I find the correct link of this (nrcan.gc.ca/energy/software-tools/7465/download.php/ang/120/0/Textbook_SWH.pdf) : 

http://www.solarthermalworld.org/sites/gstec/files/story/2015-05-31/textbook_swh.pdf

I couldn't find the first link exactly, but this paper maybe could be useful:
https://www.researchgate.net/publication/261566668_Web_application_for_thermal_comfort_visualization_and_calculation_according_to_ASHRAE_Standard_55/figures?lo=1
@chriswmackey , do you have the "title" of this: (buildingenergysoftwaretools.com/software.cfm/ID=123/pagename=alpha_list) ?

best
-Omid

**Comment by Omidmr** [comment]
@chriswmackey, and this: http://www.solemma.net/references/PLEA2004_RobinsonAndStone.pdf

-Omid

**Comment by mostaphaRoudsari** [comment]
Hi @Omidmr, Assuming @chriswmackey has updated the links inside the component this issue should be fixed now.

**Comment by chriswmackey** [comment]
@Omidmr and @mostaphaRoudsari ,
I just fixed them now.  Sorry that this fell through the cracks.  I'm already citing the Berkely comfort tool in a couple different ways so I think will leave the link to their paper out for the time being.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks for the update. We have to recreate the primers anyways.
